---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zxy.
--- DateTime: 2018/12/17 20:40
---

--[[
在Lua中，函数是严格遵循词法定界的第一类值

“第一类值”意味Lua语言中的函数与其他常见类型的值具有同等权限：
1. 一个程序可以将某个函数保存到变量中或表中
2. 可以将某个函数作为参数传递给其他函数
3. 可以将耨个函数作为其他函数的返回值返回

“词法定界”意味Lua语言中的函数可以访问包含其自身的外部函数中变量（Lua完全支持Lambda演算）
--]]

--？？Lambda演算

--[[
9.1 函数是第一类值
--]]

--第一类值得示例
a = {p = print}
a.p("Hello World")

print = math.sin
a.p(print(1))

math.sin = a.p
math.sin(10,20)

function foo(x) return 2*x end  --语法糖
foo = function(x) return 2*x end  --右边的表达式是函数构造器

--Lua语言中，所有的函数都是匿名(anonymous)的。


