---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by etcti.
--- DateTime: 2018/12/18 14:28
---
--[[
8.1 局部变量和代码块
--]]
-- 局部（local）
--[[
x = 10
local i = 1

while i<=x do
    local x = i *  2
    print(x)
    i = i + 1
end
--]]
--常见用法，声明一个局部变量foo，然后用全部变量foo对其赋初值（局部变量foo只有在声明后才能被访问）
--local foo = foo

--[[
8.2 控制结构
--]]
-- if then else
-- while
-- repeat
--[[
local line
repeat
    line = io.read()
until
    line ~= ""
print(line)
--]]
-- 数值型for
-- 泛型for  pairs、ipairs、io.lines
-- break、return和goto
--[[
goto后面紧跟着标签名，标签名可以是任意有效的标识符。标签名称前后各紧跟两个冒号，形如::name::。
--]]
-- 示例一 一个使用goto语句的状态机的示例 5.1版本不支持goto
::s1:: do
    local c = io.read(1)
    if c == '0' then goto s2
    elseif c == nil then print("ok"); return
    else goto s1
    end
end

::s2:: do
    local c = io.read(1)
    if c == '0' then goto s1
    elseif c== nil then print 'not ok'; return
    else goto s2
    end
end

goto s1

-- 示例二 一个迷宫游戏

